/*
 * Open Service Broker API
 *
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * API version: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ServiceInstanceResource struct {

	DashboardUrl string `json:"dashboard_url,omitempty"`

	MaintenanceInfo *MaintenanceInfo `json:"maintenance_info,omitempty"`

	Metadata *ServiceInstanceMetadata `json:"metadata,omitempty"`

	Parameters *Object `json:"parameters,omitempty"`

	PlanId string `json:"plan_id,omitempty"`

	ServiceId string `json:"service_id,omitempty"`
}
