/*
 * Open Service Broker API
 *
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * API version: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ServiceInstanceUpdateRequestBody struct {

	Context *Context `json:"context,omitempty"`

	Parameters *Object `json:"parameters,omitempty"`

	PlanId string `json:"plan_id,omitempty"`

	PreviousValues *ServiceInstancePreviousValues `json:"previous_values,omitempty"`

	ServiceId string `json:"service_id"`
}
