/*
 * Open Service Broker API
 *
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * API version: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type ServiceBindingRequest struct {

	AppGuid string `json:"app_guid,omitempty"`

	BindResource *ServiceBindingResouceObject `json:"bind_resource,omitempty"`

	Context *Context `json:"context,omitempty"`

	Parameters *Object `json:"parameters,omitempty"`

	PlanId string `json:"plan_id"`

	PredecessorBindingId string `json:"predecessor_binding_id,omitempty"`

	ServiceId string `json:"service_id"`
}
