/*
 * Open Service Broker API
 *
 * The Open Service Broker API defines an HTTP(S) interface between Platforms and Service Brokers.
 *
 * API version: master - might contain changes that are not yet released
 * Contact: open-service-broker-api@googlegroups.com
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package swagger

type Plan struct {

	Bindable bool `json:"bindable,omitempty"`

	BindingRotatable bool `json:"binding_rotatable,omitempty"`

	Description string `json:"description"`

	Free bool `json:"free,omitempty"`

	Id string `json:"id"`

	MaintenanceInfo *MaintenanceInfo `json:"maintenance_info,omitempty"`

	MaximumPollingDuration int32 `json:"maximum_polling_duration,omitempty"`

	Metadata *Metadata `json:"metadata,omitempty"`

	Name string `json:"name"`

	PlanUpdateable bool `json:"plan_updateable,omitempty"`

	Schemas *Schemas `json:"schemas,omitempty"`
}
